site_name: twarc
site_url: https://readthedocs.org/projects/twarc-project/
site_description: Collect Twitter JSON data from the command line.

repo_url: https://github.com/docnow/twarc
repo_name: twarc
edit_uri: edit/main/docs/

theme:
  name: "material"
  logo: images/docnow.png
  palette:
    scheme: preference

nav: 
  - Home: README.md
  - twarc2: 
    - twarc2 (en): twarc2_en_us.md
  - twarc1: 
    - twarc1 (en): twarc1_en_us.md
    - twarc1 (es): twarc1_es_mx.md
    - twarc1 (ja): twarc1_ja_jp.md
    - twarc1 (pt): twarc1_pt_br.md
    - twarc1 (sv): twarc1_sv_se.md
    - twarc1 (sw): twarc1_sw_ke.md
    - twarc1 (zw): twarc1_zw_zh.md
  - Plugins: plugins.md
  - Tutorial: tutorial.md
  - Resources: resources.md
  - Twitter Developer Access: twitter-developer-access.md 
  - Windows 10: windows10.md
  - Library API:
    - api/client.md
    - api/client2.md
    - api/library.md
    - api/expansions.md

plugins:
- search
- mkdocstrings

markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
