site_name: twarc
site_url: https://readthedocs.org/projects/twarc-project/
site_description: Collect Twitter JSON data from the command line.

repo_url: https://github.com/docnow/twarc
repo_name: twarc
edit_uri: edit/main/docs/

theme:
  name: "material"
  logo: images/docnow.png
  palette:
    scheme: preference

nav: 
  - Home: README.md
  - twarc: 
    - twarc (en): twarc_en_us.md
    - twarc (es): twarc_es_mx.md
    - twarc (ja): twarc_ja_jp.md
    - twarc (pt): twarc_pt_br.md
    - twarc (sv): twarc_sv_se.md
    - twarc (sw): twarc_sw_ke.md
    - twarc (zw): twarc_zw_zh.md
  - twarc2: 
    - twarc2 (en): twarc2_en_us.md
  - Plugins: plugins.md
  - Tutorials: tutorials.md
  - Twitter Developer Access: twitter-developer-access.md 
  - Windows 10: windows10.md
  - Library API:
    - api/client.md
    - api/client2.md
    - api/library.md
    - api/expansions.md

plugins:
- search
- mkdocstrings

markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
